version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Warsaw"
    target-branch: "develop"
    labels:
      - "bot"
      - "environment"
    commit-message:
      - "#58 - "