version: 1
update_configs:
  - package_manager: "php:composer"
    update_schedule: "weekly"
    directory: "/"
    target_branch: "develop"
    commit_message:
      prefix: "#58 - (php) "

  - package_manager: "javascript"
    update_schedule: "weekly"
    directory: "/"
    target_branch: "develop"
    commit_message:
      prefix: "#58 - (js) "
